--- #YAML:1.0
name:                Vim-Snippet-Converter
version:             0.01
abstract:            A Converter for Slippery Snippet Vim Plugin
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Copy:                    0
    File::Path:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Cornelius <c9s@aiink.com>
